// Auto-generated Verilog pixel data (12-bit RGB)
module IDLE_CHAR #(
    parameter PIXEL_WIDTH = 12,
    parameter SCREEN_WIDTH = 10,
    parameter CHAR_WIDTH_X = 32,
    parameter CHAR_WIDTH_Y = 32
) (
    input [SCREEN_WIDTH - 1:0] char_x_rom,
    input [SCREEN_WIDTH - 1:0] char_y_rom,
    input char_on,
    output [PIXEL_WIDTH - 1:0] rgb
);

parameter COLOR_0 = 12'hDBA;
parameter COLOR_1 = 12'hDCA;
parameter COLOR_2 = 12'h987;
parameter COLOR_3 = 12'h322;
parameter COLOR_4 = 12'h312;
parameter COLOR_5 = 12'h211;
parameter COLOR_6 = 12'h532;
parameter COLOR_7 = 12'h533;
parameter COLOR_8 = 12'h422;
parameter COLOR_9 = 12'hA98;

(* rom_style = "block" *) reg [CHAR_WIDTH_X * CHAR_WIDTH_Y * PIXEL_WIDTH - 1:0] pixel_map = {
    COLOR_0,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_2,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_5,     COLOR_2,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_2,     COLOR_3,     COLOR_6,     COLOR_7,     COLOR_7,     COLOR_6,     COLOR_8,     COLOR_8,     COLOR_5,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_3,     COLOR_7,     COLOR_8,     COLOR_8,     COLOR_7,     COLOR_8,     COLOR_6,     COLOR_8,     COLOR_8,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_3,     COLOR_7,     COLOR_6,     COLOR_7,     COLOR_8,     COLOR_3,     COLOR_8,     COLOR_4,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_3,     COLOR_8,     COLOR_6,     COLOR_0,     COLOR_7,     COLOR_2,     COLOR_7,     COLOR_6,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_5,     COLOR_5,     COLOR_2,     COLOR_2,     COLOR_0,     COLOR_9,     COLOR_2,     COLOR_2,     COLOR_5,     COLOR_5,     COLOR_7,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_7,     COLOR_9,     COLOR_5,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_9,     COLOR_6,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_2,     COLOR_9,     COLOR_7,     COLOR_0,     COLOR_0,     COLOR_7,     COLOR_0,     COLOR_2,     COLOR_7,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_5,     COLOR_2,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_4,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_2,     COLOR_5,     COLOR_4,     COLOR_4,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_5,     COLOR_4,     COLOR_6,     COLOR_8,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_5,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_2,     COLOR_2,     COLOR_4,     COLOR_8,     COLOR_8,     COLOR_4,     COLOR_5,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_4,     COLOR_8,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_5,     COLOR_4,     COLOR_4,     COLOR_8,     COLOR_4,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_8,     COLOR_4,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_4,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_8,     COLOR_8,     COLOR_4,     COLOR_5,     COLOR_9,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_8,     COLOR_4,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_9,     COLOR_5,     COLOR_4,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_8,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_9,     COLOR_9,     COLOR_3,     COLOR_4,     COLOR_6,     COLOR_6,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_4,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_5,     COLOR_4,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_5,     COLOR_8,     COLOR_6,     COLOR_6,     COLOR_6,     COLOR_8,     COLOR_4,     COLOR_6,     COLOR_6,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_5,     COLOR_4,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_4,     COLOR_6,     COLOR_6,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_2,     COLOR_2,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_7,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_4,     COLOR_4,     COLOR_8,     COLOR_4,     COLOR_5,     COLOR_2,     COLOR_2,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_2,     COLOR_6,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1, 
    COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_7,     COLOR_4,     COLOR_4,     COLOR_5,     COLOR_5,     COLOR_5,     COLOR_4,     COLOR_4,     COLOR_5,     COLOR_5,     COLOR_4,     COLOR_3,     COLOR_5,     COLOR_5,     COLOR_8,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_5,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_7,     COLOR_4,     COLOR_4,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_5,     COLOR_3,     COLOR_5,     COLOR_5,     COLOR_1,     COLOR_5,     COLOR_3,     COLOR_5,     COLOR_1,     COLOR_4,     COLOR_4,     COLOR_7,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_5,     COLOR_6,     COLOR_8,     COLOR_3,     COLOR_1,     COLOR_8,     COLOR_6,     COLOR_5,     COLOR_1,     COLOR_7,     COLOR_7,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_9,     COLOR_3,     COLOR_8,     COLOR_8,     COLOR_4,     COLOR_0,     COLOR_3,     COLOR_8,     COLOR_3,     COLOR_9,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_1,     COLOR_0,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_6,     COLOR_6,     COLOR_3,     COLOR_7,     COLOR_9,     COLOR_5,     COLOR_3,     COLOR_8,     COLOR_5,     COLOR_9,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_0,     COLOR_0,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0 
};

assign rgb = (char_on) ? pixel_map[char_y_rom * CHAR_WIDTH_X + char_x_rom ] : 12'hFFF;

endmodule
