// Auto-generated Verilog pixel data (12-bit RGB)
module IDLE_CHAR #(
    parameter PIXEL_WIDTH = 12,
    parameter SCREEN_WIDTH = 10,
    parameter CHAR_WIDTH_X = 40,
    parameter CHAR_WIDTH_Y = 40
) (
    input [SCREEN_WIDTH - 1:0] char_x_rom,
    input [SCREEN_WIDTH - 1:0] char_y_rom,
    input char_on,
    output [PIXEL_WIDTH - 1:0] rgb
);

parameter COLOR_0 = 12'hFFF;
parameter COLOR_1 = 12'hFFF;
parameter COLOR_2 = 12'h777;
parameter COLOR_3 = 12'h000;
parameter COLOR_4 = 12'h000;
parameter COLOR_5 = 12'h778;
parameter COLOR_6 = 12'h777;
parameter COLOR_7 = 12'h111;
parameter COLOR_8 = 12'h113;
parameter COLOR_9 = 12'h016;
parameter COLOR_10 = 12'h015;
parameter COLOR_11 = 12'h014;
parameter COLOR_12 = 12'h003;
parameter COLOR_13 = 12'h112;
parameter COLOR_14 = 12'h112;
parameter COLOR_15 = 12'h888;

(* rom_style = "block" *) reg [CHAR_WIDTH_X * CHAR_WIDTH_Y * PIXEL_WIDTH - 1:0] pixel_map = {
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_4,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_4,     COLOR_4,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_2,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_2,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_7,     COLOR_8,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_10,     COLOR_11,     COLOR_12,     COLOR_13,     COLOR_14,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_10,     COLOR_12,     COLOR_13,     COLOR_3,     COLOR_2,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_15,     COLOR_14,     COLOR_8,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_12,     COLOR_13,     COLOR_14,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_10,     COLOR_12,     COLOR_13,     COLOR_3,     COLOR_6,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_12,     COLOR_11,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_12,     COLOR_11,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_3,     COLOR_13,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_9,     COLOR_5,     COLOR_6,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_13,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_4,     COLOR_13,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_9,     COLOR_5,     COLOR_6,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_13,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_5,     COLOR_9,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_8,     COLOR_15,     COLOR_15,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_5,     COLOR_9,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_8,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_8,     COLOR_3,     COLOR_6,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_8,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_8,     COLOR_3,     COLOR_6,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_8,     COLOR_9,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_9,     COLOR_8,     COLOR_6,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_2,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_6,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_2,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_15,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_6,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_15,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_6,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_6,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_3,     COLOR_13,     COLOR_5,     COLOR_5,     COLOR_5,     COLOR_5,     COLOR_11,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_3,     COLOR_13,     COLOR_5,     COLOR_5,     COLOR_5,     COLOR_5,     COLOR_11,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_7,     COLOR_7,     COLOR_8,     COLOR_8,     COLOR_8,     COLOR_8,     COLOR_7,     COLOR_7,     COLOR_11,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_14,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_3,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_7,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_7,     COLOR_12,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_14,     COLOR_7,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_7,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_12,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_11,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_14,     COLOR_7,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_10,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_14,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_11,     COLOR_9,     COLOR_9,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_14,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_5,     COLOR_9,     COLOR_3,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_5,     COLOR_9,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_7,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_5,     COLOR_9,     COLOR_3,     COLOR_3,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_9,     COLOR_5,     COLOR_9,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_14,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_6,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_14,     COLOR_3,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_9,     COLOR_6,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_7,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_14,     COLOR_7,     COLOR_3,     COLOR_9,     COLOR_15,     COLOR_6,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_7,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_13,     COLOR_11,     COLOR_13,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_1,     COLOR_5,     COLOR_3,     COLOR_3,     COLOR_12,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_3,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_13,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_1,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_15,     COLOR_4,     COLOR_3,     COLOR_12,     COLOR_12,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_3,     COLOR_12,     COLOR_12,     COLOR_12,     COLOR_13,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_4,     COLOR_4,     COLOR_3,     COLOR_15,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_2,     COLOR_4,     COLOR_13,     COLOR_10,     COLOR_10,     COLOR_10,     COLOR_11,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_3,     COLOR_11,     COLOR_10,     COLOR_10,     COLOR_10,     COLOR_12,     COLOR_3,     COLOR_5,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_3,     COLOR_13,     COLOR_10,     COLOR_10,     COLOR_10,     COLOR_11,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_3,     COLOR_11,     COLOR_10,     COLOR_10,     COLOR_10,     COLOR_12,     COLOR_3,     COLOR_5,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_5,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_15,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_3,     COLOR_5,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0, 
    COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_1,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_1,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_15,     COLOR_1,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0,     COLOR_0

};

assign rgb = pixel_map[(char_y_rom * CHAR_WIDTH_X + char_x_rom) * PIXEL_WIDTH +: PIXEL_WIDTH];

endmodule
